### PR TITLE
Unify barstools into single src tree that matches package structure

### PR DESCRIPTION
**Pull request by chick**
This is a pretty massive PR that does several things
- Slurps in `plsi-mdf` into this repo. 
- Has a single top level `src/` dir that includes all
- Fixes a lot of tests that relied on each other's side effects
This will make maintaining this repo easier as tests are unified and easier to run.
There are still some cleanup things to do. 
In particular tests that call directly into a `StageMain` subclass's `main` method while capturing stdout can create some very difficult to debug tests.

### CODE REVIEW

**Review by edwardcwang — APPROVED** [review]
Generally seems fine to me, but the others should take a look too.

**Review by ekiwi — APPROVED** [review]
LGTM

**Comment by jerryz123** [comment]
Can we bump barstools in chipyard as well with this?

**Comment by chick** [comment]
@jerryz123 
Also this is built against chisel 3.5 and iotesters 2.5 and that may require a bit of tinkering to chipyard
I think there might be a tweak or two to regarding with build.sbt and packages
I'll try it soon

**Review by harrisonliew — APPROVED** [review]

**Pull request merged**
