### PR TITLE
Fix for ucb-bar/firrtl#459, reworking annotation API

### PR DESCRIPTION
**Pull request by azidar**
Please don't merge until after ucb-bar/firrtl#464 is merged.

### CODE REVIEW

**Comment by colinschmidt** [comment]
Ok thanks, I'll keep my eye on the firrtl PR

**Comment by azidar** [comment]
This should be merged now.

**Comment by shunshou** [comment]
@azidar is that all that changed or are there more things that need to be done? Seems like you did a lot of work on Annotations recently?

**Comment by azidar** [comment]
The other changes should be captured in the type system, and not everything has merged.

Other changes have been to make Pass extend Transform, which, once it is merged, may affect you, and implement the RenameMap stuff, which should make your transforms easier (you don't need to lower the name yourself anymore).

**Comment by azidar** [comment]
If you'd like, I can update your passes once the other PR's get merged.

**Comment by shunshou** [comment]
That'd be super appreciated. ._. /severely time constrained

**Comment by shunshou** [comment]
@azidar do you mind looking at my transforms too? Hopefully it's not too painful to see what goes where...

**Comment by azidar** [comment]
I thought I did? Sorry, which ones?

**Comment by shunshou** [comment]
Stuff in the clkgen and pads directories (they were in an unmerged PR when you made changes...). Might be annoying to figure out what's going on, so I can also fix it like a month down the line when I start using this stuff...

**Comment by azidar** [comment]
checkout #13

**Pull request merged**
