### PR TITLE
Getting barstools to support building the FFT generator

### PR DESCRIPTION
**Pull request by chick**
Bump versions of chisel3 and chisel-iotesters
Bump scalaVersion to 2.12.10
Bump sbt version to 1.3.8
Do a bunch of icky stuff so IsClkModule works
Change a bunch of Vec calls to VecInit
Change several chiselCloneType to chiselTypeOf

### CODE REVIEW

**Comment by chick** [comment]
I'm not sure why any of this was necessary, perhaps I'm missing something in my build environment, but I gave up trying to figure it out, because it was blocking any progress on the FFT. Hopefully somebody can point out to me what's going on here.

**Comment by edwardcwang** [comment]
Are you referring to dsptools FFT? or some other FFT?

**Comment by chick** [comment]
Angie's FFT, it's in a private repo

**Comment by colinschmidt** [comment]
I would recommend using the versions of chisel et al that are used in chipyard I believe that is 3.3.x and 1.3.x, as that will have the most robust support with CI running and such.

**Comment by chick** [comment]
Closing this for now.

**Pull request closed without merging**
