### PR TITLE
bump mdf for ucb-bar/plsi-mdf#7

### PR DESCRIPTION
**Pull request by timsnyder-siv**

### CODE REVIEW

**Review by edwardcwang — APPROVED** [review]

**Comment by chick** [comment]
@timsnyder-siv Can I go ahead and merge this. It looks ok but I get nervous when things have been sitting this long

**Comment by timsnyder** [comment]
Since it's just fixing an underlying compiler warning and @edwardcwang merged mdf to master, it should be fine to merge.  I'll add that I've been using this myself without it being merged since December and everything is fine for me.    Thanks for getting it closed out.

**Comment by timsnyder-siv** [comment]
Also, when properly logged in with my work account, I'm able to hit the merge button and I'm happy to do so if you'd like.

**Comment by chick** [comment]
Thanks @timsnyder-siv

**Pull request merged**
