### PR TITLE
fix for chipsalliance/firrtl#2095 chipsalliance/firrtl#1730

### PR DESCRIPTION
**Pull request by sequencer**
ask @chick @ekiwi to review.

### CODE REVIEW

**Review by chick — APPROVED** [review]
lgtm

**Comment by sequencer** [comment]
> Can you try to debug why this fails in CI?

Seems a CI broken, sbt cache not working, it was building from old FIRRTL.

> Also, it might be possible to just replace the local and etc functions with the implementation from firrtl.
We could also consider changing import firrtl.Utils._ to import firrtl.Utils and then just prefixing method calls with Utils. where appropriate.


Sure will fix it today.

**Comment by chick** [comment]
@sequencer Sorry, but I cannot get the changed inport in  MacroCompiler or SynFlops to compile 
```
import firrtl.Utils.{and => _, or => _, not => _, _}
```
Get errors
```
sbt:root> test
[info] Compiling 4 Scala sources to /Users/chick/Adept/dev/masters/barstools/macros/target/scala-2.12/classes ...
[error] /Users/chick/Adept/dev/masters/barstools/macros/src/main/scala/barstools/macros/MacroCompiler.scala:11:8: value and is not a member of object firrtl.Utils
[error] import firrtl.Utils.{and => _, or => _, not => _, _}
[error]        ^
Elaborating design...
Elaborating design...
Done elaborating.
Done elaborating.
[error] /Users/chick/Adept/dev/masters/barstools/macros/src/main/scala/barstools/macros/SynFlops.scala:6:8: value and is not a member of object firrtl.Utils
[error] import firrtl.Utils.{and => _, or => _, not => _, _}
[error]        ^
Elaborating design...
Done elaborating.
[error] two errors found
```
Please advise

**Comment by sequencer** [comment]
@chick have another try ;p

**Comment by sequencer** [comment]
@chick CI failed:
> 2021-07-12 03:11:56,682 shutdown-hooks-run-all ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2.

I think travis should be blamed.

**Comment by chick** [comment]
We just approved PR #103 which uses github actions for testing. Do you need to rebase on new master or can you just restart the tests

**Comment by sequencer** [comment]
I don’t know why this broke ci. I’ll dig this tonight.

**Comment by ekiwi** [comment]
> I don’t know why this broke ci. I’ll dig this tonight.

I think CI was broken before you added this. Rebasing on master should do the trick.

Also, it looks like @chick may have already included some of these fixes as part of: https://github.com/ucb-bar/barstools/pull/109

**Comment by ekiwi** [comment]
Seems like everything on master is compiling against the latest chisel + firrtl.

**Pull request closed without merging**
