### PR TITLE
Move passes from pfpmp to barstools.

### PR DESCRIPTION
**Pull request by colinschmidt**
Simply include the pfpmp passes for now. Integrated with hurricane-chip and tested there.

More work to be done but some needs extra features and the rest can be done incrementally as tapeout schedule permits.

### CODE REVIEW

**Comment by shunshou** [comment]
@colinschmidt any idea if there's some better way to generalize reading Yaml files? Seems like between Annotations, MemLib stuff, your stuff, and the pad pass I'm working on, there's just lots of different Yaml readers... that are 90% the same, save for implicits. :\

**Comment by colinschmidt** [comment]
I don't think I've added YA-YAML reader, I was trying to just reuse the one that chisel/firrtl use for annotations. I also haven't worked with YAML much at all, so I think we should ask @chick @azidar if they have.
But I do agree it would be nice to somehow standardize on this. I actually am just vaguely remembering a conversation with @jackkoenig on Friday about datatypes in annotations which may or may not be related.

**Comment by shunshou** [comment]
Btw - is the plan to have multiple branches? B/c if not, you're free to merge (unless we're hoping to get some more legit code review from people... but for the sake of tapeout time constraints, I'm kind of meh about that >_>...).

**Comment by colinschmidt** [comment]
I think its better to have one branch. Will merge later today.

**Comment by shunshou** [comment]
Okiedokes. I have my own branch going, but I don't expect any conflict. Still experimenting with templating, etc.

**Comment by colinschmidt** [comment]
As to YAML parsing see ucb-bar/firrtl#452

**Pull request merged**
