### PR TITLE
utils.DiGraph was being being confused with the DigGraph in firrtl.

### PR DESCRIPTION
**Pull request by chick**
This led to pathological exceptions
No such method error on accessing a lazy val.
InstanceGraph seemed also to be a duplicate of firrtl code, and was used only in commented out code so I deleted it too.

***

IOPadSpec fails no two tests but these seem to be at least an ordinary error. And should be debugged separately

### CODE REVIEW

**Comment by chick** [comment]
@stevobailey @shunshou @albert-magyar @colinschmidt 
This fixes a really bizarre method not found error/exception when running tests.  IOPadSpec fails to tests.  I don't think it's related to the DiGraph code but it might be.  Let me know if you think I need to dig into that

**Comment by chick** [comment]
@colinschmidt Wow, that was a record push to merge.

**Comment by shunshou** [comment]
Oh gosh sorry! Yeah it's b/c I stuck in Albert's stuff before it got merged with Firrtl. And I was running into the same issue when doing sbt publish-local so I commented out the use in ClkGen for now... I guess that wasn't the only problem. My bad!

**Comment by shunshou** [comment]
I'm not using IOPad stuff for now (prob won't be in time for tapeout...), but I'll clean it up for a future tapeout hopefully around July.

**Pull request merged**
