### PR TITLE
Upstream MemConf and use it (with some slight tweaks)

### PR DESCRIPTION
**Pull request by jwright6323**
This goes with https://github.com/freechipsproject/firrtl/pull/1041 to upstream MemConf

### CODE REVIEW

**Comment by jwright6323** [comment]
The firrtl PR is done, this should go in whenever rocket-chip bumps to a newer firrtl version and we bump `rebar` to that rocket-chip.

**Comment by jwright6323** [comment]
@colinschmidt when #57 goes in, I'd like to rebase this onto that, and then merge it before you bump barstools in project-template

**Comment by colinschmidt** [comment]
Ok noted.

**Comment by jwright6323** [comment]
This was incorporated into https://github.com/ucb-bar/barstools/commit/82636b3ff43ecf6a0f0a7d46ebc2456b31e9703f

**Pull request closed without merging**
